### ISSUE TITLE
Download button bug in IE

### ISSUE THREAD

**Issue by arnaudvedy** [COSD-PANDA/seaboard#152]
Download button is unresponsive in IE - throws the following error:
![ie_download](https://cloud.githubusercontent.com/assets/22329288/23880235/955833de-080f-11e7-8025-c1a6a957242c.png)

**Comment by MrMaksimize** [comment]
As I think about this, this is part of gracefully degrading to a browser with no js.  

Need to think about how to inject urls directly, as well as track
