### ISSUE TITLE
Tour

### ISSUE THREAD

**Issue by MrMaksimize** [COSD-PANDA/seaboard#189]

**Comment by MrMaksimize** [comment]
http://github.hubspot.com/shepherd/

**Comment by MrMaksimize** [comment]
http://linkedin.github.io/hopscotch/multipage2.html

**Comment by MrMaksimize** [comment]
http://zurb.com/playground/jquery-joyride-feature-tour-plugin

**Comment by udrysa** [comment]
i like this too
